apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
        - name: python-api
          image: python-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          envFrom:
            - configMapRef:
                name: redis-cm
            - secretRef:
                name: redis-secret
